services:
  go-llvm-dev:
    tty: true
    image: tiny-compiler:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspace
    environment:
      - DOT_DIR=/workspace
    volumes:
      - .:/workspace
      - go-mod-cache:/go/pkg
      - build-cache:/root/.cache
    command: /bin/sh -c "$CMD"
    network_mode: host

volumes:
  go-mod-cache:
  build-cache:
