FROM golang:1.24-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
  llvm-19 llvm-19-dev make graphviz && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

RUN go env -w GOPROXY=https://goproxy.cn,direct
